dvsa/cvs-svc-test-results

src/functions/getTestResultsByTesterStaffId.ts
src/models/ITestResultFilter.ts
tests/unit/getTestResultsByTesterStaffId.unitTest.ts

CVSB-7623 got lost during Typescript Migration. Reimplementing here. No other changes.

CVSB-8592 - reimplement CVSB-7623: filter on testStatus

---

src/services/TestResultsService.ts
tests/unit/generateExpiryDate.unitTest.ts

Expiry Date calculations on last day of month fail due to "start of day" issue. No tests, as tests were already correctly covering the issue but pass when not last day of the month.
Issue actually happens at line 310, when the current datetime is checked to see if it is before the datetime derived from regOrFirstUseDate, which is just a date so the time defaults to the start of that day. By forcing the derived datetime  to be the end of the day, all calculations proceed as expected.

CVSB-11853

---

package-lock.json
package.json
src/assets/Enums.ts
src/models/CommonSchema.ts
src/models/ITestResultPayload.ts
src/models/TestResultsSchemaMotorcycleSubmitted.ts
src/services/TestResultsService.ts
tests/unit/insertTestResult.unitTest.ts

Improvement changes related to https://jira.dvsacloud.uk/browse/CVSB-13903
The ticket is covering the iteration on Test results API specs v27, to cover the optionality of the vehicleClass attribute for vehicles that are not motorcycle, due to the specialist testing. For motorcycles. the attribute remains mandatory as it is needed to derive the test code.

CVSB-13903 vehicleClass mandatory only for motorcycles

---

src/services/TestResultsService.ts
tests/unit/updateTestResults.unitTest.ts

Backend service update, to allow testerEmailAddress and testStationType to be updated with new values

CVSB-15036 - tester email and test station editable

---

src/services/TestResultsService.ts
tests/unit/updateTestResults.unitTest.ts

https://jira.dvsacloud.uk/browse/CVSB-15456
This ticket is required because, there is no concept of creating a visit on VTM, hence test records newly entered on VTM do not have a visit, therefore the backend cannot ensure that the test time stamps are within the timeframes of the visit (since the visit doesnt exist)
Therefore, if a test result does not have a visit, the validation does not apply.

Feature/cvsb 15456 - Do not throw 404 is no visit is found for test-result

---

package-lock.json
package.json
src/functions/getTestResultsBySystemNumber.ts
src/services/TestResultsService.ts
src/utils/GetTestResults.ts
tests/unit/generateCertificateNumber.unitTest.ts
tests/unit/generateExpiryDate.unitTest.ts
tests/unit/getTestResultsBySystemNumberFunction.unitTest.ts

Substituted date-fns with moment.js and fixed bug https://jira.dvsacloud.uk/browse/CVSB-14539. 
This effectively sets expiryDates at the beginning of the UTC day and can be displayed in both, UTC and British timezones correctly.
This change will require a change on the expiryDates already generated as T23:59:59.999Z

Expiry dates appearing 1 day more than expected in ATF/RTK/TEST HISTORY

---

serverless.yml
src/assets/Enums.ts
src/config/config.yml
src/functions/archiveTestResults.ts
src/functions/updateTestResults.ts
src/models/CommonSchema.ts
src/models/ITestResult.ts
src/models/TestResultsDAO.ts
src/models/test-types/testTypesSchemaPut.ts
src/models/test-types/testTypesSchemaSpecialistTestsPut.ts
src/services/TestResultsService.ts
src/utils/formatErrorMessage.ts
tests/resources/test-results.json
tests/unit/archiveTestResults.unitTest.ts
tests/unit/archiveTestResultsFunction.unitTest.ts
tests/unit/configuration.unitTest.ts
tests/unit/updateTestResults.unitTest.ts
tests/unit/updateTestResultsFunction.unitTest.ts

This ticket covers the ability for a user to archive a test type. A new CTA will be present on the test record view mode. A modal will appear once the user selects the new archive CTA where they can confirm to archive the test type they have selected.
'statusUpdatedFlag' - new attribute to identify which test type in a test result is to be archived
https://jira.dvsacloud.uk/browse/CVSB-14406

Feature/cvsb 14406 - archive test-types

---

src/handlers/expiry/providers/DateProvider.ts
src/handlers/expiry/providers/TestDataProvider.ts
src/services/TestResultsService.ts
tests/unit/expiry/TestDataProvider.unitTest.ts
tests/unit/generateExpiryDate.unitTest.ts

Changes to handle expiry date format for legacy data and to throw error if any other format of date occurs.
Original ticket - (changes on 18928 branch still)
https://jira.dvsacloud.uk/browse/CVSB-18928 
closed in favour of
https://jira.dvsacloud.uk/browse/CVSB-18931

feat(cvsb-18931): update date validation and recent expiry logic - changes on branch 18928

---

docs/test-results-api.yml
src/models/validators/CommonSchema.ts

Update the service to allow potf testStationType to be used when posting a test result.
[https://dvsa.atlassian.net/browse/VTA-737](VTA-737)

VTA-737: Allow POTF testStationTypes to be used when starting visit in VTA

---

docs/test-results-api.yml

[link to ticket number](https://dvsa.atlassian.net/browse/CB2-4674)
- PUT returns a TestResult on success - Swagger says it just returns a 200
- Path param for the PUT is actually systemNumber not testResultId

chore(cb2-4674): update put test result api definition

---

src/models/validators/CommonSchema.ts

Reverting validation changes to testTypeId and testerStaffId to disallow null in order to bring in line with regression pack tests.
[cb2-4934](https://dvsa.atlassian.net/browse/CB2-4934)

feat(cb2-4939): reverting changes to testtypeid and testerstaffid

---

tests/unit/generateExpiryDate.unitTest.ts

Registration Anniversary date of test record (15) being used in failing tests is 31/10/2022, tests have been failing since 31/08/2022 as we are now within 2 months of that date which is throwing off the logic in strategy.getExpiryDate method. 
This fix corrects the regnDate of the test record being used in the failing tests. 
(The test record itself has not been modified as it is used by a number of other tests)
[VTA-866](https://dvsa.atlassian.net/browse/VTA-866)

VTA-866: fix broken unit tests

---

src/assets/Enums.ts

TRL Free Loaded Retests were missing from the Amend groups. This is to put them back in so we can support amending them on VTM. 
[Link to Jenkins Report](https://jenkins.cvs.dvsacloud.uk/job/UPDATE__BRANCH/job/job_feature_test_backend/lastSuccessfulBuild/DVSA_20CVS_20Backend_20Automation/)
The only failing/errored tests are unrelated to this ticket as they do not refer to test type ID 199.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6287)

feat(cb2-6287): added support for trl free loaded retest to group 10

---

package-lock.json
src/handlers/VehicleTestController.ts
src/handlers/expiry/providers/TestDataProvider.ts
src/models/TestResultsDAO.ts
tests/unit/updateTestResults.unitTest.ts

There currently exists some validation of Test Results which looks for a single Activity for the date, tester and test station of the Test.  If it finds more than one Activity it returns an error and the Test cannot be amended. PO has confirmed that it is possible that there could be more than one Activity for a date, tester and station.
- bump `minimatch` to stop the husky hooks failing
[Jenkins regression pack test](https://jenkins.cvs.dvsacloud.uk/job/UPDATE__BRANCH/job/job_feature_test_backend/2432/DVSA_20CVS_20Backend_20Automation/) on feature branch.
[CB2-6380](https://dvsa.atlassian.net/browse/CB2-6380)

feat(cb2-6380): remove activity check

---

README.md
src/handlers/VehicleTestController.ts
tests/unit/updateTestResults.unitTest.ts

There is a requirement to handle linked tests independently. Because of the discrepancy with the validation between the `POST` and the `PUT` endpoint, this solution seems to be the cleanest way of updating ONLY one test without updating other linked tests. It effectively flattens test records as far as the `PUT` endpoint and VTM (amend) are concerned. If the endpoint receives only one test type, then it adds in the old test types that it got from the database. Tested manually in feature branch and works as intended.
There is no requirement currently to update more than one linked test in the same `PUT` request in VTM. Even if there was, with the change only adding extra linked tests to the test coming in if there is only one linked test, this would still be possible.
This solution only …

feat(cb2-5532): ability to handle linked tests

---

src/assets/Enums.ts
src/utils/validationUtil.ts
tests/unit/insertTestResult.unitTest.ts

Updated the logic/validation to ensure that certificate number / expiry date are provided for LEC test types when expected, as per story.
[VTA-903](https://dvsa.atlassian.net/browse/VTA-903)

VTA-903: Capture LEC Certificate Number

---

src/models/validators/CommonSchema.ts
src/models/validators/test-types/testTypesSchemaSpecialistTestsPut.ts
tests/resources/test-results-post.json
tests/resources/test-results.json
tests/unit/insertTestResult.unitTest.ts
tests/unit/updateTestResults.unitTest.ts

Changes to allow Specialist tests to be created/updated when certificate number/expiry date/anniversary date are hidden
Regression pack run:
https://jenkins.cvs.dvsacloud.uk/job/UPDATE__BRANCH/job/job_feature_test_backend/2497/
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6092)

feature(cb2-6092): customise emissions section

---

src/utils/mappingUtil.ts
tests/unit/mappingUtil.unitTest.ts

Allow createdById and createdByName entered by the user to persists for desk based assessments.
[CB2-6549](https://dvsa.atlassian.net/browse/CB2-6549)

task(cb2-6894): desk assessment created by

---

package-lock.json
package.json

SNYK has raised a new security issue since [PR294](https://github.com/dvsa/cvs-svc-test-results/pull/294) was created last week. After merging the PR to develop this morning it is now failing the CI checks.
This PR removes the problematic package as it was not used. It also removes a load of other unused packages.

chore(cb2-1): remove unused packages

---

src/handlers/expiry/providers/DateProvider.ts
src/handlers/expiry/strategies/HgvTrlFirstTestStrategy.ts
tests/unit/expiry/HgvTrlFirstTestStrategy.unitTest.ts
tests/unit/generateExpiryDate.unitTest.ts

If a HGV or Trailer has a first test and its first registration anniversary is in the month of February 2022, and the test is performed before the anniversary date, the test's expiry date will be 28/02/2024 rather than 29/02/2024.
[CB2-7139](https://dvsa.atlassian.net/browse/CB2-7139)
Certificate created on the develop branch with the old code.
Certificate created on the vtmdev-1 branch with the new code.
The changes were deployed to VTMDEV-1 and regression packs run.
Note: the two failed tests are usual for the 'full' BE regression pack.
Note: the failed test is seen for previous runs of the 'Annual Cert' BE regression pack.

CB2-7139 Fix expiry date calculation for leap years

---

package-lock.json
scripts/setup.ts
tests/integration/getTestResultsBySystemNumber.intTest.ts
tests/resources/test-results.json
tests/unit/getTestResultsByTesterStaffId.unitTest.ts

There was a test failing when running the integration tests for test-results. It was caused by the test data falling outside of the two year window for a search by system number with no search parameters.
[CB2-7277](https://dvsa.atlassian.net/browse/CB2-7277)

CB2-7277 Fix breaking integration test

---

src/handlers/VehicleTestController.ts

Vehicle class is not present for LGV and cars
[CB2-7844](https://dvsa.atlassian.net/browse/CB2-7844)

fix(7844): makes vehicle class optional in update

---

src/handlers/VehicleTestController.ts

Vehicle class is not present for LGV and cars, hence adding an optional check to avoid error.
[CB2-7844](https://dvsa.atlassian.net/browse/CB2-7844)

fix(cb2-7844): makes vehicle class optional in test-result update

---

src/models/validators/CommonSchema.ts

Updated the CommonSchema Joi schema so that the testResultsCommonSchema now allows empty strings in the numberOfWheelsDriven field.
[[link to ticket number](https://dvsa.atlassian.net/browse/CB2-7942)]

fix(CB2-7942): CommonSchema Joi Update

---

src/models/validators/TestResultsSchemaPSVCancelled.ts
src/models/validators/TestResultsSchemaPSVSubmitted.ts

Changed the maximum length of the VRM field to 9 for PSV as per original requirements instead of the previous maximum length of 8 characters long.
[CB2-8250](https://dvsa.atlassian.net/browse/CB2-8250)

fix(cb2 8250) vrm maximum field length for psv

---

src/handlers/expiry/providers/DateProvider.ts
tests/unit/expiry/HgvTrlAnnualTestStrategy.unitTest.ts
tests/unit/expiry/HgvTrlFirstTestStrategy.unitTest.ts
tests/unit/expiry/HgvTrlMostRecentExpiryStrategy.unitTest.ts
tests/unit/expiry/PsvDefaultExpiryStrategy.unitTest.ts
tests/unit/expiry/PsvMostRecentExpiryStrategy.unitTest.ts
tests/unit/expiry/PsvRegistrationAnniversaryStrategy.unitTest.ts

This PR is an amalgamation of 3 tickets (VTA-114, VTA-156 & VTA-157), which themselves were new tickets based on historical tickets CVSB-18816 and CVSB-19880.
Essentially, all testing scenarios are still relevant and would benefit from being added to the unit tests. 
As part of this spike, it was also identified that the PSV anniversary expiry logic was not quite right, as it fell over in the event an inputDate was 29th February on a leap year. Logic has been updated as part of this PR which now means the expiry date generated matches that which the PO's originally provided in the historical tickets.
Branch has been rebased against the latest develop (18/5/23)
[VTA-1311](https://dvsa.atlassian.net/browse/VTA-1311)

VTA-1311: Additional Testing Scenarios

---

src/models/validators/test-types/testTypesSchemaDeskBasedTestsPut.ts
tests/unit/validationUtil.unitTest.ts

secondaryCertificateNumber is not a required field for group 5 tests for HGV, hence removing the validation
[CB2-9796](https://dvsa.atlassian.net/browse/CB2-9796)

fix(cb2-9796): remove validation for hidden field

---

package-lock.json
src/models/validators/TestResultsSchemaCarSubmitted.ts
src/utils/validationUtil.ts
tests/unit/validationUtil.unitTest.ts

Update tests to allow no odometer reading on IVA & add unit tests.
[CB2-9716](https://dvsa.atlassian.net/browse/CB2-9716?atlOrigin=eyJpIjoiZWFiMjgwY2M3YzJiNGI0YTllMmI5MzAzZTQ2NDQ4YTAiLCJwIjoiaiJ9)

feat(cb2-9716): Make odometer readings optional for IVA tests

---

docs/test-results-api.yml
src/models/validators/CommonSchema.ts
src/models/validators/SpecialistTestsCommonSchemaCancelled.ts
src/models/validators/SpecialistTestsCommonSchemaSubmitted.ts
src/models/validators/test-types/testTypesSchemaSpecialistTestsPut.ts

The referenceNumber property of custom defects has been made optional for specialist test types only, non specialist test types remain mandatory.
[https://dvsa.atlassian.net/browse/CB2-10477](CB2-10477)

feat(cb2 10477): making specialist test type referenceNumber optional

---

docs/test-results-api.yml
package-lock.json
package.json
src/models/ITestResult.ts
src/models/validators/CommonSchema.ts
src/models/validators/SpecialistTestsCommonSchemaCancelled.ts
src/models/validators/SpecialistTestsCommonSchemaSubmitted.ts
src/models/validators/TestResultsSchemaCarSubmitted.ts
src/models/validators/TestResultsSchemaHGVCancelled.ts
src/models/validators/TestResultsSchemaHGVSubmitted.ts
src/models/validators/TestResultsSchemaLGVSubmitted.ts
src/models/validators/TestResultsSchemaMotorcycleSubmitted.ts
src/models/validators/TestResultsSchemaPSVCancelled.ts
src/models/validators/TestResultsSchemaPSVSubmitted.ts
src/models/validators/TestResultsSchemaTRLCancelled.ts
src/models/validators/TestResultsSchemaTRLSubmitted.ts
src/models/validators/test-types/testTypesSchemaDeskBasedTestsPut.ts
src/models/validators/test-types/testTypesSchemaPut.ts
src/models/validators/test-types/testTypesSchemaSpecialistTestsPut.ts
src/utils/mappingUtil.ts
src/utils/validationUtil.ts
tests/resources/test-results-post.json
tests/resources/test-results.json
tests/unit/insertTestResult.unitTest.ts
tests/unit/updateTestResults.unitTest.ts

Replacing ivaDefects with requiredStandards will allow re-use of the same objects for MSVA as well as IVA.
This also brings terminology in-line with DVSA policy and VTA/VTM apps.
**As per PR comments, it was agreed that the PUT validation for desk based tests should be consistent with the POST, so that was also updated as part of this change.**
[CB2-10828](https://dvsa.atlassian.net/browse/CB2-10828)

CB2-10828: Refactor test-results service from ivaDefects to requiredStandards

---

src/models/ITestResult.ts
src/models/validators/CommonSchema.ts
tests/unit/insertTestResult.unitTest.ts

This change is to make the reference number optional, instead of required in the 
[CB2-10932](https://dvsa.atlassian.net/browse/CB2-10932)

CB2-10932: Reference number optional in the JOI schemas

---

src/assets/Enums.ts
src/handlers/VehicleTestController.ts
tests/resources/test-results-post.json
tests/unit/insertTestResult.unitTest.ts

Adds logic to ensure that IVA and MSVA tests set their cert number as the test number, when a cert number is not provided in the payload
[link to ticket number](https://dvsa.atlassian.net/jira/software/c/projects/CB2/boards/973?selectedIssue=CB2-11180)

feat(cb2-11180): Populate certificate number (with test number) for failed IVA and MSVA tests

---

src/handlers/VehicleTestController.ts
src/handlers/expiry/providers/TestDataProvider.ts
src/models/TestResultsDAO.ts
tests/unit/insertTestResult.unitTest.ts

resolves issue with returning 500 instead of 201 when sending duplicate test to create endpoint 
fixes returning empty string for provider name rather than null
corrects issue with the automation pack failing
[link to ticket number]()

chore(cb2-11271): aws sdk upgrade - resolving issue post update

---

src/handlers/VehicleTestController.ts
src/handlers/expiry/providers/TestDataProvider.ts
tests/unit/expiry/TestDataProvider.unitTest.ts
tests/unit/insertTestResult.unitTest.ts

resolves issue with sending 400 and incorrect error message for creating a duplicate testId
reformats the errors for get database methods so they'll return usefully and with correct error codes. 
Ignores put method errors as they all default to 500 code with the message which remains the same in aws-sdk v3
[[link to ticket number]()](https://dvsa.atlassian.net/browse/CB2-11271)

chore(cb2-11271): upgrade cvs-svc-test-results from aws sdk v2 to v3
