dvsa/cvs-svc-test-results

src/models/TestResultsSchemaCancelled.js
src/models/TestResultsSchemaSubmitted.js

Fix validations after previous merge conflicts

CVSB-3761 Fixes after merge

---

.nsprc
package-lock.json
package.json

1 "medium" vulnerability remaining as no fix currently available.

CVSB-5108 - upgrade vulnerable dependencies.

---

src/models/TestResultsSchemaCancelled.js
src/models/TestResultsSchemaSubmitted.js
tests/resources/test-results.json

Reverts dvsa/cvs-svc-test-results#79 as per release cut meeting

Revert "added prohibitionIssued for defects" CVSB-3025

---

src/services/TestResultsService.ts
tests/unit/insertTestResult.unitTest.ts

Made changes for certNum generation for LEC TestTypes. 
These changes are to be merged into 4927.
Please review

CVSB-8936: Certificate number for LEC tests are overwritten - HGVT only

---

package.json
serverless.yml
tests/integration/getTestResultsByVin.intTest.ts
tests/integration/insertTestResults.intTest.ts

Enabled integration tests for test-results.
Havent updated the packages yet, will do that. 
Also jenkins build was successful for these changes.

CVSB-9041 Test Results:  Re-implement integration tests

---

src/models/CommonSchema.ts

Update to CommonSchema with new values coming from ETL for PSVs

CVSB-12530 Added vehicleClass validation values

---

src/assets/Enums.ts
src/services/TestResultsService.ts
tests/unit/generateExpiryDate.unitTest.ts

https://github.com/dvsa/cvs-svc-test-results.git

feature/CVSB-11509  PSV expiry dates calculation for annual + coif tests.

---

src/assets/Enums.ts
src/services/TestResultsService.ts
tests/unit/generateExpiryDate.unitTest.ts

Creating a new PR to merge the missed commits. Also fixed the conflicts with develop

CVSB-11334 and CVSB-11509

---

src/assets/Enums.ts
src/models/CommonSchema.ts
src/models/test-types/testTypesSchemaPut.ts
src/services/TestResultsService.ts
tests/resources/test-results.json
tests/unit/getTestResultsBySystemNumber.unitTest.ts
tests/unit/updateTestResults.unitTest.ts

https://jira.dvsacloud.uk/browse/CVSB-11504

Feature/cvsb 11504 - testTypes validations

---

src/assets/Enums.ts
src/config/config.yml
src/models/CommonSchema.ts
src/models/ITestResult.ts
src/models/ITestResultPayload.ts
src/models/TestResultsDAO.ts
src/models/test-types/testTypesSchemaPut.ts
src/services/TestResultsService.ts
tests/resources/test-results.json
tests/unit/updateTestResults.unitTest.ts

added necessary audit details on the test-result object. These audit details are required for updating tech-records
https://jira.dvsacloud.uk/browse/CVSB-10316

Feature/cvsb 10316 - Update tech record status based on the result for First test and Notifiable alterations

---

src/assets/Enums.ts
src/config/config.yml
src/models/CommonSchema.ts
src/models/ITestResult.ts
src/models/TestResultsDAO.ts
src/models/test-types/testTypesSchemaPut.ts
src/services/TestResultsService.ts
tests/unit/updateTestResults.unitTest.ts

https://jira.dvsacloud.uk/browse/CVSB-12378

Feature/cvsb 12378 - testType start/end timestamp and testCode validation

---

src/assets/Enums.ts
src/models/test-types/testTypesSchemaSpecialistTestsPut.ts
src/services/TestResultsService.ts
tests/unit/updateTestResults.unitTest.ts

Backend service update to allow the update of specialist tests
https://jira.dvsacloud.uk/browse/CVSB-10372

Feature/cvsb 10372 - Update specialist tests

---

src/models/ITestResultPayload.ts
tests/resources/test-results.json

https://jira.dvsacloud.uk/browse/CVSB-17424
Added entries in seed file needed for automated tests

CVSB-9644 - added entries in seed file with missing countryOfReg

---

src/models/TestResultsDAO.ts
src/services/TestResultsService.ts
tests/unit/TestResultsDao.unitTest.ts
tests/unit/getTestResultsByTesterStaffId.unitTest.ts

Bugfix to retrieve all test-results when generating reports

CVSB-18659 Added pagination to getTesterByStaffId

---

src/assets/strategy-mapping.json
tests/resources/duplicated-mapping.json
tests/unit/expiry/ExpiryDateStrategyFactory.unitTest.ts

https://jira.dvsacloud.uk/browse/CVSB-18875
Fixing the overlapping mapping

CVSB-18875 Bugfix strategy mapping json

---

src/services/TestResultsService.ts
src/utils/LoggingUtil.ts
tests/unit/LoggingUtil.unitTest.ts

This solution adresses 2 tickets:
https://jira.dvsacloud.uk/browse/CVSB-18785
https://jira.dvsacloud.uk/browse/CVSB-19029

feature/CVSB-18785 Added CloudWatch reporting for 10 year old tyre defects and advisories

---

src/services/TestResultsService.ts
tests/unit/generateCertificateNumber.unitTest.ts
tests/unit/insertTestResult.unitTest.ts

(Only HGV & TRL)
ROADWORTHINESS PASS - SHOULD GENERATE A CERTIFICATE NUMBER
ROAD WORTHINESS FAIL- SHOULD NOT GENERATE A CERTIFICATE NUMBER
https://jira.dvsacloud.uk/browse/CVSB-13638

CVSB-13638 - do not generate certificate number for roadworthiness fail

---

package-lock.json
serverless.yml
src/handlers/VehicleTestController.ts
src/handlers/expiry/providers/TestDataProvider.ts
src/models/FilterValue.ts
src/models/ITestResultFilter.ts
src/models/TestResultsDAO.ts
src/models/index.ts
src/services/TestResultsService.ts
src/utils/mappingUtil.ts
src/utils/validationUtil.ts
tests/integration/getTestResultsByTesterStaffId.intTest.ts
tests/unit/TestResultsDao.unitTest.ts
tests/unit/expiry/TestDataProvider.unitTest.ts
tests/unit/generateExpiryDate.unitTest.ts
tests/unit/getTestResultsBySystemNumber.unitTest.ts
tests/unit/getTestResultsByTesterStaffId.unitTest.ts
tests/unit/getTestResultsDeletionFlag.unitTest.ts
tests/unit/insertTestResult.unitTest.ts
tests/unit/updateTestResults.unitTest.ts

Update to getTesterByStaffId and getTestResultsBySystemNumber:
[link to ticket number](https://jira.dvsacloud.uk/browse/CVSB-18676)

chore(cvsb-18676): update logic for pagination for get functions

---

package-lock.json
package.json

Resolved high vulnerabilities identified by npm audit
https://jira.dvsacloud.uk/browse/VTA-568

feat(VTA-568): updated high vulnerabilities

---

package-lock.json
package.json

[VTA-505](https://jira.dvsacloud.uk/browse/VTA-505)

feat(VTA-568): updated high vulnerabilities (#231)

---

src/models/TestResultsDAO.ts

The fix is to change that logic to be where test end time <= visit end time.
[link to ticket number](https://dvsa.atlassian.net/browse/VTA-679)

feat(VTA-679): corrected dynamo filter expression

---

src/models/validators/test-types/testTypesSchemaPut.ts

Align the put request for emissions with the post request
[CB2-3949](https://dvsa.atlassian.net/browse/CB2-3949)

feat(cb2-3949): align emissions validation with post

---

src/assets/Enums.ts
src/functions/getTestResultsBySystemNumber.ts
src/functions/getTestResultsByTesterStaffId.ts
src/handler.ts
src/models/HTTPError.ts
src/models/HTTPResponse.ts
src/models/ILogMessage.ts
src/utils/Validator.ts
tests/unit/getTestResultsBySystemNumberFunction.unitTest.ts
tests/unit/getTestResultsByTesterStaffIdFunction.unitTest.ts

Add validation for parameters and additional request/response logging to Test Result Service.
[link to ticket number](https://dvsa.atlassian.net/browse/VTA-693)

feat(VTA-695): added parameter validation and additional logging

---

src/assets/Enums.ts
src/functions/getTestResultsBySystemNumber.ts
src/functions/getTestResultsByTesterStaffId.ts
src/handler.ts
src/models/HTTPError.ts
src/models/HTTPResponse.ts
src/models/ILogMessage.ts
src/utils/Validator.ts
tests/unit/getTestResultsBySystemNumberFunction.unitTest.ts
tests/unit/getTestResultsByTesterStaffIdFunction.unitTest.ts

Merge from holding branch VTADEV-31 into develop
[VTA-695](https://dvsa.atlassian.net/browse/VTA-695)

VTA-695: Add validation for parameters and additional request/response logging

---

src/assets/Enums.ts

Amend PSV Desk Based Tests Group 2: subtask. 
Adding DBT codes to whitelist so that amendments can be made
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-6532)

feat(CB2-6532): Amend PSV Desk Based Tests Group 2: subtask

---

src/assets/Enums.ts
src/utils/validationUtil.ts
tests/resources/test-results.json

Ability to record a HGV/TRL desk based tests - Groups 4
[CB2-6550](https://dvsa.atlassian.net/browse/CB2-6550)
- Scape "validateMandatoryTestResultFields" if type of test is 'desk-based'.
- **_Fixed_** integration test `getTestResultsBySystemNumber.intTest.ts` failing in failing in develop.

feat(cb2-6550): optional fields

---

src/assets/Enums.ts

fix(cb2-0000): fix lint errors

---

src/utils/mappingUtil.ts

Fix linting error in pipeline:

fix(*): fix linting error in pipeline

---

src/assets/Enums.ts

Create a HGV Type Approved Tractor Unit DBA
Add test type
[link](https://dvsa.atlassian.net/browse/CB2-7541)

feature(cb2-7541): Create a HGV Type Approved Tractor Unit DBA

---

src/assets/Enums.ts
src/models/validators/test-types/testTypesSchemaDeskBasedTestsPut.ts

Amend a HGV Type Approved Tractor Unit DBA
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-7543)

feat(cb2-7543): Amend a HGV Type Approved Tractor Unit DBA

---

src/handlers/VehicleTestController.ts

Copy of #323 into develop
Create light vehicle group 2
already tested in vtmdev-1
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-7633)

fix(cb2-7633): query test types with multiple vehiclesSubclasses (#323)

---

package-lock.json
package.json
patches/dynamodb-localhost+0.0.9.patch

Use patch-package to fix the build and test issues in the pipeline.

chore: fixes tools-setup issue with dynamodb-local download url

---

src/utils/LoggingUtil.ts

mark defects as optional to avoid null pointer exception
[CB2-7726](https://dvsa.atlassian.net/browse/CB2-7726)

fix(cb2-7726): missing optional defects change

---

src/assets/Enums.ts
src/utils/validationUtil.ts

[CB2-7727](https://dvsa.atlassian.net/browse/CB2-7727)

feat(cb2-7727): remove the small trailer type

---

src/handlers/VehicleTestController.ts
src/models/ITestResultPayload.ts
src/models/validators/TestResultsSchemaCarSubmitted.ts
src/models/validators/TestResultsSchemaLGVSubmitted.ts
src/models/validators/TestResultsSchemaMotorcycleSubmitted.ts
tests/unit/generateExpiryDate.unitTest.ts

* feat(cb2-6876): expiry date now uses test end timestamp
* feat(cb2-6876): add console log
* feat(cb2-6876): add another console log
* feat(cb2-6876): tweaked console logs
* feat(cb2-6876): tweaked console logs again
* feat(cb2-6876): add unit test
* feat(cb2-6876): extra unit test for hgv/trl tests
* fix(cb2-7726): light vehicles should have optional defects (#332)
---------
[link to ticket number]()

feat(cb2-6876) - modify expiry date calculations (#330)

---

src/assets/Enums.ts
src/models/validators/test-types/testTypesSchemaDeskBasedTestsPut.ts

Add validations
[CB2-7533](https://dvsa.atlassian.net/browse/CB2-7533)

feat(cb2-7533): add lgv DBA group 5 validation

---

src/assets/Enums.ts
src/models/validators/test-types/testTypesSchemaDeskBasedTestsPut.ts

Add IVA test type id to enums
[CB2-7533](https://dvsa.atlassian.net/browse/CB2-7533)

fix(cb2-7533): Add IVA test type id to enums

---

src/assets/Enums.ts
src/models/validators/test-types/testTypesSchemaDeskBasedTestsPut.ts
src/utils/mappingUtil.ts
tests/unit/getTestResultsBySystemNumberFunction.unitTest.ts

[CB2-7652](https://dvsa.atlassian.net/browse/CB2-7652)

feature(cb2-7652): allow getting cancelled tests

---

src/models/validators/CommonSchema.ts
src/models/validators/TestResultsSchemaTRLSubmitted.ts
src/models/validators/test-types/testTypesSchemaDeskBasedTestsPut.ts
src/models/validators/test-types/testTypesSchemaPut.ts
src/utils/validationUtil.ts
tests/unit/updateTestResults.unitTest.ts

Allow failed tests to submit without certain dates
[link to ticket number]()

fix(cb2-8109): allow failed tests to send without dates

---

src/handlers/expiry/providers/TestDataProvider.ts

This change is to allow test results to show up that are in the future. However, it is worth noting that there is a restriction on how far in the future that it will reach. Currently, it is set to 01/01/2040
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-8864)

feat(cb2-8864): Display tests in future

---

src/assets/Enums.ts

[CB2-7849](https://dvsa.atlassian.net/browse/CB2-7849)

feat(cb2-7849): new dba tests for psv

---

src/handlers/expiry/providers/TestDataProvider.ts
src/utils/mappingUtil.ts
tests/unit/getTestResultsBySystemNumberFunction.unitTest.ts

[link to ticket number](https://dvsa.atlassian.net/browse/CB2-8864)

(CB2 8864): View tests in the future

---

package-lock.json
package.json
src/models/ITestResult.ts
src/models/validators/SpecialistTestsCommonSchemaCancelled.ts
src/models/validators/SpecialistTestsCommonSchemaSubmitted.ts
src/models/validators/TestResultsSchemaCarSubmitted.ts
src/models/validators/TestResultsSchemaHGVCancelled.ts
src/models/validators/TestResultsSchemaHGVSubmitted.ts
src/models/validators/TestResultsSchemaLGVSubmitted.ts
src/models/validators/TestResultsSchemaMotorcycleSubmitted.ts
src/models/validators/TestResultsSchemaPSVCancelled.ts
src/models/validators/TestResultsSchemaPSVSubmitted.ts
src/models/validators/TestResultsSchemaTRLCancelled.ts
src/models/validators/TestResultsSchemaTRLSubmitted.ts
src/utils/mappingUtil.ts
src/utils/validationUtil.ts
tests/resources/test-results-post.json
tests/resources/test-results.json
tests/unit/generateExpiryDate.unitTest.ts
tests/unit/insertTestResult.unitTest.ts

Adds IVA defects array to test results
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-9874)

feat(cb2-9874): added iva defects to the test record payloads (#364)

---

package-lock.json
package.json
src/models/ITestResult.ts
src/models/validators/SpecialistTestsCommonSchemaCancelled.ts
src/models/validators/SpecialistTestsCommonSchemaSubmitted.ts
src/models/validators/TestResultsSchemaCarSubmitted.ts
src/models/validators/TestResultsSchemaHGVCancelled.ts
src/models/validators/TestResultsSchemaHGVSubmitted.ts
src/models/validators/TestResultsSchemaLGVSubmitted.ts
src/models/validators/TestResultsSchemaMotorcycleSubmitted.ts
src/models/validators/TestResultsSchemaPSVCancelled.ts
src/models/validators/TestResultsSchemaPSVSubmitted.ts
src/models/validators/TestResultsSchemaTRLCancelled.ts
src/models/validators/TestResultsSchemaTRLSubmitted.ts
src/utils/mappingUtil.ts
src/utils/validationUtil.ts
tests/resources/test-results-post.json
tests/resources/test-results.json
tests/unit/generateExpiryDate.unitTest.ts
tests/unit/insertTestResult.unitTest.ts

Reverts dvsa/cvs-svc-test-results#365

Revert "feat(cb2-9874): added iva defects to the test record payloads (#364)"

---

src/models/validators/SpecialistTestsCommonSchemaCancelled.ts
src/models/validators/SpecialistTestsCommonSchemaSubmitted.ts
src/models/validators/TestResultsSchemaCarSubmitted.ts
src/models/validators/TestResultsSchemaHGVCancelled.ts
src/models/validators/TestResultsSchemaHGVSubmitted.ts
src/models/validators/TestResultsSchemaLGVSubmitted.ts
src/models/validators/TestResultsSchemaMotorcycleSubmitted.ts
src/models/validators/TestResultsSchemaPSVCancelled.ts
src/models/validators/TestResultsSchemaPSVSubmitted.ts
src/models/validators/TestResultsSchemaTRLCancelled.ts
src/models/validators/TestResultsSchemaTRLSubmitted.ts
src/utils/validationUtil.ts
tests/resources/test-results-post.json
tests/unit/insertTestResult.unitTest.ts
tests/unit/updateTestResults.unitTest.ts

Update the GET and PUT to implement IVA defects.
[link to ticket number](https://dvsa.atlassian.net/browse/CB2-10339)

CB2-10339: Update Test Results service GET and PUT endpoints for new data structure

---

.github/workflows/pr-checks.yml

build(runs-on): update runner for CI job
